src/validators/actix.rs
Return 4xx (client error) when the client is missing required data in the request, in this case it is the `Authorization` header. Also going out on a limb saying its a bad request (4xx series) if the server is unable to parse whatever data is that header. Previously, the `.unwrap()` on the Option would panic the actix-web server. This returns the 4xx response instead of crashing/panic.
I ran `cargo fmt` and got a bunch of changes, so left those out of the PR.
=> handle missing request header

src/apis/actor_tokens_api.rs
Hey @DarrenBaldwin07! Amazing work with this library :tada: 
I'll be opening a couple of performance-related PRs for this crate, if that's OK by you
In this one, if `local_var_status.is_success()` we deserialize directly into an `ActorToken` instead of allocating a temporary String
=> actor_tokens_api: less latency in happy path

src/models/session.rs
I was getting serde errors on clerk api response of the `verify_session` api call. After inspecting the response payload, the `last_active_at`, `expire_at`, `abandon_at` values were 13 digit numbers, so naturally i32 deserialization would fail.
=> fix(session): i32 to i64 for last_active, expire_at, abandon_at

Cargo.toml
This PR adds `rustls-tls` and `native-tls` feature flags and changes the default to be `rustls-tls`.
Closes #33.
=> Use rustls by default and add feature for native-tls

Cargo.toml, README.md, examples/actix.rs, examples/axum.rs, src/clerk.rs, src/models/email_address_verification.rs, src/validators/actix.rs, src/validators/authorizer.rs, src/validators/axum.rs, src/validators/mod.rs
This MR adds support for the Axum framework.
=> Add support for Axum framework

src/validators/authorizer.rs
This PR enables `validate_nbf` on `jsonwebtoken::Validation` per the [Clerk docs](https://clerk.com/docs/backend-requests/handling/manual-jwt#verify-the-token-signature).
=> Validate the nbf claim of the jwt

Cargo.toml, README.md, src/validators/mod.rs
This PR adds `axum` and `actix` feature flags that enable the Axum and Actix validators respectively. This is breaking since the `actix` validator is no longer available by default.
Closes #37.
=> Add feature flags for axum and actix validators

Cargo.toml, src/validators/authorizer.rs
This PR replaces `openssl` with the `rng` and `rand` crates which don't require additional dependencies.
=> Remove dependency on openssl in tests

Cargo.toml
This PR makes the `actix-web` crate optional and adds it to the `actix` feature. Somehow missed it in #39.
=> Make actix-web dependency optional

src/validators/authorizer.rs
This PR replaces some potential panics in `validate_jwt` with errors and changes the signature of `validate_jwt` to return `Result<Jwt, Error>` instead of `Result<(bool, Jwt), bool>`.
=> Remove panics and return ClerkError from validate_jwt

src/validators/authorizer.rs
`sid` is not a recommended claim according to the guidelines (https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-token-claims). Recently, we encountered an issue where the server returned a 401 error because JSON parsing failed on a token that lacked `sid`.
=> Make non-recommended JWT claims optional

src/clerk.rs, src/validators/authorizer.rs
`to_string` would result in a URL like `myclerkdomain.com/rest/v1GetUser` instead of the proper `myclerkdomain.com/rest/v1/user/{user_id}`. This uses the enum fn `as_str` to get the proper path for a given endpoint.
This PR stacks on https://github.com/DarrenBaldwin07/clerk-rs/pull/48
=> [bug] make dynamic routes work properly

README.md
This adds a badge for rust docs, to make it easier to reach from the `README`.
=> Add badge for rustdocs

src/validators/authorizer.rs
According to the clerk docs - https://clerk.com/docs/backend-requests/resources/session-tokens
There are additional claims in the JWT token for backend requests that can be useful to glean information about the user's active organization and permissions.
Implementation inspired from the official clerk go sdk - https://github.com/clerk/clerk-sdk-go/blob/3411ef39ca0f1f01a91fd6fa766c032d2f9683a9/clerk/session_claims.go#L16
Updated the unit tests to reflect the new claims
Related to #52
=> [Claims] Add all possible backend claims to ClerkJWT

src/validators/authorizer.rs
This is a followup to #56 to make the fields of `ActiveOrganization` public so that they can be accessed to get `org` information from a `ClerkJwt` struct. 
As far as I can tell this shouldn't require any updates to tests or documentation, but I'm happy to make updates as needed.
=> Make fields of ActiveOrganization struct public

src/apis/users_api.rs
This change cleans up some references vs. ownership usage to reduce the amount of unneeded allocation done in the query building.
=> api: Reduce allocations in `get_user_list`

src/clerk.rs, src/validators/authorizer.rs
This may be useful for some users of the structs.
This change also transforms some documentation to Rust doc comments.
=> minor: Mark some structs as `Clone`

src/validators/authorizer.rs, src/validators/axum.rs
This PR passes the validated `ClerkJWT` so that it can be used in the routes by the `Extension` extractor: `Extension(jwt): Extension<ClerkJwt>`.
=> Pass ClerkJWT

src/validators/authorizer.rs
Updated `act` to reflect the documentation
=> [Claims] Add act to claims

Cargo.toml
This change bumps some of the old dependencies. I'm also happy to break this into a separate changes if so desired.
Notably, this bumps `reqwest` to a version that mitigates [RUSTSEC-2024-0336](https://rustsec.org/advisories/RUSTSEC-2024-0336).
=> chore: Bump dependencies

src/validators/authorizer.rs
Addresses https://github.com/DarrenBaldwin07/clerk-rs/pull/56#issuecomment-2312625893
This is useful for custom templates/compatibility with future updates to theclerk jwt schema
=> [ClerkJWT] Deserialize any remaining fields in jwt

Cargo.toml, README.md, examples/actix.rs, examples/axum.rs, src/validators/actix.rs, src/validators/authorizer.rs, src/validators/axum.rs, src/validators/jwks.rs, src/validators/mod.rs
This PR adds a `JwksProvider` trait which is used by `ClerkAuthorizer` to retrieve JWKs for validating requests.
It provides `SimpleJwksProvider` which reqeusts the JWKS from Clerk on every request, and `MemoryCacheJwksProvider` that caches the JWKS in memory. The expiration time of `MemoryCacheJwksProvider` is optional and configurable. The behavior when an key that isn't in the cache is requested is also configurable: don't refresh the JWKS, always refresh the JWKS, and refresh the JWKS if the cache is older than a certain duration.
This PR also splits `validate_jwt` into `validate_jwt` which takes a `JwksProvider` and `validate_jwt_with_key` which takes a `JwksKey`. The Axum and Actix middlewares are also updated to take a `JwksProvider` instead of a `ClerkConfiguration`.
Closes #45.
=> Add JwksProvider to allow for caching of the JWKS

src/validators/authorizer.rs
This may be useful for people who may want to use it with `validate_jwt()`.
=> Expose `ClerkAuthorizer::jwks_provider` publicly

docs/CreateOrganizationRequest.md, docs/OrganizationsApi.md, src/apis/organizations_api.rs, src/models/create_organization_request.rs
Update the `CreateOrganizationRequest` model to match Clerk's backend API docs for creating an organization: https://clerk.com/docs/reference/backend-api/tag/Organizations#operation/CreateOrganization
- Allow organization creation without an assigned admin user by making the `created_by` field optional
- Allow custom creation timestamps when creating an organization by adding the optional `created_at` field
I've tested this in a separate project but let me know if there's somewhere that integration or other tests should be added.
=> Update Create Organization Request

examples/axum.rs
Resolves #81 by adding a minimal example for using an extractor on a route handler.
=> Refactor examples/axum.rs to include protected route example.
